DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS games;

CREATE TABLE games (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    picture VARCHAR(255),
    content TEXT NOT NULL,
    subtitle VARCHAR(255),
    created_at DATETIME DEFAULT NOW()
    );

CREATE TABLE comments (
id INT AUTO_INCREMENT PRIMARY KEY,
zelda_id INT NOT NULL,
content VARCHAR(255) NOT NULL,
created_at DATETIME DEFAULT NOW(),
FOREIGN KEY (zelda_id) REFERENCES games(id) ON DELETE CASCADE
);